name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - prd
      - stg
    paths:
      - deployments.yaml

jobs:
  release-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract deployment data
        id: parse-yaml
        uses: './.github/actions/setup'

      - name: Docker login
        run: |
          echo ${{ secrets.DOCKER_REPO_PAT }} \
          | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin

      - uses: azure/setup-helm@v4.2.0

      - name: Configure kubeconfig
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }}
        run: |
          mkdir ~/.kube
          echo "$KUBECONFIG_B64" | base64 -d > ~/.kube/config

      - name: Check kubectl connection
        run: kubectl get nodes

      # the reason its here is that im building prefect anyway.
      # TODO: build all images, including prefect's, in their respective repos
      - name: Build Docker image for service
        run: |
          docker build \
            -t ${{ secrets.DOCKER_REGISTRY }}/restful-ml:${{ steps.parse-yaml.outputs.tag }} \
            "https://github.com/stateful-ml/stateful-ml.git#${{ steps.parse-yaml.outputs.tag }}:workspace" \
            --file service/Dockerfile

      - name: Helm Install restful-ml
        run: |
          helm repo add stateful-ml https://stateful-ml.github.io/infra/
          helm install \
            restful-ml stateful-ml/restful-ml \
            -f ./deployments.yaml \
            --set repository=${{ secrets.DOCKER_REGISTRY }}/restful-ml \
            --set version=${{ steps.parse-yaml.outputs.version }} \
            --namespace ${{ github.ref_name }}


  release-prefect:
    runs-on: ubuntu-latest
    container:
      image: prefecthq/prefect:3.0.8-python3.11
    steps:
      ## alternative to container for `act`
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'

      # - run: pip install prefect==3.0.8

      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract deployment data
        id: parse-yaml
        uses: './.github/actions/setup'

      - name: Docker login
        run: |
          echo ${{ secrets.DOCKER_REPO_PAT }} \
          | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Checkout tag in different repository
        uses: actions/checkout@v3
        with:
          repository: stateful-ml/stateful-ml
          ref: ${{ steps.parse-yaml.outputs.tag }}
          path: stateful-ml
          token: ${{ secrets.STATEFUL_ML_PAT }}

      - name: Deploy Prefect
        env:
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        # wild, i NEED to ditch prefect
        run: |
          pip install --no-cache -r stateful-ml/workspace/shared/requirements.txt
          pip install --no-cache -r stateful-ml/workspace/pipelines/requirements.txt
          python stateful-ml/workspace/pipelines/deploy.py \
            --image-registry ${{ secrets.DOCKER_REGISTRY }} \
            --image-repo pipeful-ml
            --env ${{ github.ref_name }} \
            --version ${{ steps.parse-yaml.outputs.version }} \
            ${{ steps.parse-yaml.outputs.gnu-model-params }}

      - name: Deduplicate staging deployments
        if: ${{ github.ref_name == 'prd' }}
        run: |
          python .github/workflows/deduplicate-deployments.py \
            --version ${{ steps.parse-yaml.outputs.version }}
