name: Release
on:
  push:
    branches:
      - prd
      - stg

jobs:
  release-helm:
    runs-on: docker:dind
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get code version from config
        id: get-tag
        uses: mikefarah/yq@master
        with:
          cmd: yq '.tag' 'deployments.yml'

      # the reason its here is that im building prefect anyway.
      # TODO: build all images, including prefect's, in their respective repos
      - name: Build Docker image for service
        run: |
          docker build -t restful-ml:${{ steps.get-tag.outputs.result }} "https://github.com/stateful-ml/stateful-ml.git#${{ steps.get-tag.outputs.result }}:workspace" --file service/

      - name: Helm Install restful-ml
        run: |
          helm install restful-ml stateful-ml/restful-ml -f ./deployments.yaml --namespace "${{ github.ref_name }}"


  release-prefect:
    runs-on: ubuntu-latest
    # container:
    #   image: prefecthq/prefect:3.0.8-python3.11
    steps:
      ## alternative to container for `act`
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'

      # - run: pip install prefect==3.0.8

      - name: Checkout
        uses: actions/checkout@v3

      - name: Load yaml
        id: load-yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -o=json . 'deployments.yaml'

      - name: Build prefect deployment parameters
        id: build-deployment-params
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.models[] | "--" + .project + " " + .identifier' 'deployments.yaml' | tr '\n' ' '

      - name: Build prefect pipeline version
        id: build-version
        run: echo "version=${{ join(fromJson(steps.load-yaml.outputs.result).models.*.identifier, '-') }}" >> "$GITHUB_OUTPUT"

      - name: Checkout tag in different repository
        uses: actions/checkout@v3
        with:
          repository: stateful-ml/stateful-ml
          ref: ${{ fromJson(steps.load-yaml.outputs.result).tag }}
          path: stateful-ml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Prefect
        run: |
          python stateful-ml/pipelines/deploy.py --env ${{ github.ref_name }} --version ${{ steps.build-version.outputs.version }} ${{ steps.build-deployment-params.outputs.result }}

      - name: Deduplicate staging deployments
        if: ${{ github.ref_name == 'prd' }}
        run: |
          python .github/workflows/deduplicate-deployments.py --version ${{ steps.build-version.outputs.version }}
